export const COLORS: Array<Color.IColor> = [
    {
        name: "red",
        text: "text-red-500",
        hover: "bg-red-400",
        border: "border-red-400",
    },
    {
        name: "orange",
        text: "text-orange-500",
        hover: "bg-orange-400",
        border: "border-orange-400",
    },
    {
        name: "amber",
        text: "text-amber-500",
        hover: "bg-amber-400",
        border: "border-amber-400",
    },
    {
        name: "yellow",
        text: "text-yellow-500",
        hover: "bg-yellow-400",
        border: "border-yellow-400",
    },
    {
        name: "lime",
        text: "text-lime-500",
        hover: "bg-lime-400",
        border: "border-lime-400",
    },
    {
        name: "green",
        text: "text-green-500",
        hover: "bg-green-400",
        border: "border-green-400",
    },
    {
        name: "emerald",
        text: "text-emerald-500",
        hover: "bg-emerald-400",
        border: "border-emerald-400",
    },
    {
        name: "teal",
        text: "text-teal-500",
        hover: "bg-teal-400",
        border: "border-teal-400",
    },
    {
        name: "cyan",
        text: "text-cyan-500",
        hover: "bg-cyan-400",
        border: "border-cyan-400",
    },
    {
        name: "sky",
        text: "text-sky-500",
        hover: "bg-sky-400",
        border: "border-sky-400",
    },
    {
        name: "blue",
        text: "text-blue-500",
        hover: "bg-blue-400",
        border: "border-blue-400",
    },
    {
        name: "indigo",
        text: "text-indigo-500",
        hover: "bg-indigo-400",
        border: "border-indigo-400",
    },
    {
        name: "violet",
        text: "text-violet-500",
        hover: "bg-violet-400",
        border: "border-violet-400",
    },
    {
        name: "purple",
        text: "text-purple-500",
        hover: "bg-purple-400",
        border: "border-purple-400",
    },
    {
        name: "fuchsia",
        text: "text-fuchsia-500",
        hover: "bg-fuchsia-400",
        border: "border-fuchsia-400",
    },
    {
        name: "pink",
        text: "text-pink-500",
        hover: "bg-pink-400",
        border: "border-pink-400",
    },
    {
        name: "rose",
        text: "text-rose-500",
        hover: "bg-rose-400",
        border: "border-rose-400",
    },
];
